### ISSUE TITLE
How to set up Multiple paths

### ISSUE THREAD

**Issue by mrbarletta** [keajs/kea-localstorage#1]
Awesome work - I really love Kea, after a while, everything seems easy.

Well, almost :)

I created a path  in kea({options like this `path: () => ["shownBubbles"],` I also added the path in the store ( otherwise doesn't work) like this:
```
export default getStore({
    paths:['shownBubbles'],
    plugins: [localStoragePlugin, sagaPlugin],
});

```
But if a add the `persist:true` to more than one reducer  (in the same big Logic file ) then the information get overwritten. Its like all the reducers share the same path instead of allocating their own key. 

Thanks!

**Comment by mariusandra** [comment]
Hey! You found a bug! :)

Indeed all the reducers were sharing the path of the logic store itself. 

I released `0.2.0` that should have it fixed.

**Comment by mrbarletta** [comment]
Oh dear, You don't imagine how much I appreciate your promptness! 
I will try it out :)

**Comment by mrbarletta** [comment]
@mariusandra  - I still don't get it. Seems that I have to manually define a Key? 

currently if I set up persistence for more than 1 reducer the app will collapse,  with 1 reducer I have to do nothing, just use it but when another reducer is persisting, I have the same issue.

I thought the key thing was to accommodate multiple instances of the logic, not multiple reducers. what do you think?

**Comment by mrbarletta** [comment]
Closing as fixed
